name: Jeerp Project
description: 

url: "http://jeerp.github.io"

paginate: 10

markdown: rdiscount

# translation tags
t:
  ita:
    home:  "Home"
    about: "About"
    developer : "Sviluppatori"
    documentation : "Documentazione"
    demo : "Demo online"
    use : "Usa online"
    contact : "Contatti"
    language : "Lingua"
    components : "Componenti"
    installation : "Installazione"
    main_menu : "Menù principale"
    electric_menu : "Menù consumi elettrici"
    ele_dash_stat : "Dashboard statica elettrica"
    ele_dash_inter : "Dashboard interattiva elettrica"
    clim_menu : "Menù gestione clima"
    clim_dash : "Dashboard climatica di visualizzazione e controllo"
    back_to_top : "Torna su"
  eng:
    home:  "Home"
    about: "About"
    developer : "Developer"
    documentation : "Documentation"
    demo : "Online demo"
    use : "Online use"
    contact : "Contacts"
    language : "Language"
    components : "Components"
    installation : "Installation"
    main_menu : "Main menu"
    electric_menu : "Electric consumption menu"
    ele_dash_stat : "Electric static dashboard"
    ele_dash_inter : "Electric interactive dashboard"
    clim_menu : "Climatic management menu"
    clim_dash : "Climatic dashboard for visualization and management"
    back_to_top : "Back to top"